# App-Configuration
spring.application.name=hotel-management
server.port=8081

# JSP-Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# JPA-Configuration
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DB-Configuration-H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver


#----------------------------------------------------Not Well Mannered--------------------------------------------------
#App-Configuration
#spring.application.name=hotel-management
#server.port=8081

#JSP-Configuration
#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

#JPA-Configuration
#spring.jpa.defer-datasource-initialization=true
#spring.jpa.show-sql=true

#Hibernate-Configureation
#spring.jpa.hibernate.ddl-auto=update

#DB-Configuration-H2
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb

#? Add Hibernate DDL auto:
#properties
#spring.jpa.hibernate.ddl-auto=update
#so your entities automatically create/update tables in H2.

#? Enable SQL logging while learning:
#properties
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#? Specify H2 username and password explicitly (optional):
#properties
#spring.datasource.username=sa
#spring.datasource.password=

#? Add driver explicitly (optional):
#properties
#spring.datasource.driver-class-name=org.h2.Driver
